/* Feminine Strength Co. — Master Client Platform v2
   One application. Authenticated users determine which client data is loaded.
   No client name, client ID, or client programming is hard-coded here.
*/
const CFG=window.FSC_CONFIG||{};
const hasSupabase=!!(CFG.SUPABASE_URL&&CFG.SUPABASE_PUBLISHABLE_KEY&&window.supabase);
const sb=hasSupabase?window.supabase.createClient(CFG.SUPABASE_URL,CFG.SUPABASE_PUBLISHABLE_KEY):null;

const APP={session:null,profile:null,client:null,selectedClient:null,coachClients:[],exercises:[],templates:[],workouts:[],resources:[],checkinQuestions:[],todayCheckin:null,nutritionSettings:null,nutritionLogs:[],movementLogs:[],progressEntries:[],notes:[],activeTab:'today',mode:'client',timers:new Map()};

const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const today=()=>new Date().toISOString().slice(0,10);
const fmtDate=d=>d?new Date(d+'T12:00:00').toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'}):'—';
const fmtLong=d=>d?new Date(d+'T12:00:00').toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'}):'—';
const dayName=()=>new Date().toLocaleDateString('en-US',{weekday:'long'});
const initials=name=>String(name||'FSC').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();
const isCoach=()=>APP.profile?.role==='coach';
const currentClient=()=>APP.selectedClient||APP.client;
function toast(msg){const t=document.getElementById('toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2600)}
function errorToast(msg){console.error(msg);toast(msg)}
function setLoading(on){document.body.classList.toggle('loading',on)}
function label(x){return({today:'Today',training:'Training',nutrition:'Nutrition',movement:'Movement',progress:'Progress',resources:'Resources'})[x]||x}

async function init(){
  renderShell();
  if(!hasSupabase){renderSetup();return}
  setLoading(true);
  try{
    const {data,error}=await sb.auth.getSession();if(error)throw error;
    APP.session=data.session;
    if(!APP.session){renderLogin();return}
    await loadIdentity();
    if(isCoach()){
      APP.mode='coach';await loadCoachHub();renderCoachHub();
    }else{
      await loadClient(APP.session.user.id);
      if(!APP.client){renderNoClient();return}
      await loadClientData(APP.client.id);renderClient();
    }
  }catch(e){renderError(e)}finally{setLoading(false)}
  sb.auth.onAuthStateChange((_event,session)=>{APP.session=session;if(!session)location.reload()});
}

function renderShell(){document.getElementById('app').innerHTML='<div class="shell"><header class="topbar" id="topbar"></header><nav class="nav hide" id="nav"></nav><main id="main"></main></div>'}
function renderSetup(){document.getElementById('main').innerHTML='<section class="center-card card"><div class="eyebrow">Feminine Strength Co.</div><div class="title">Platform setup</div><p class="sub">Add your existing public anon/publishable key to <code>config.js</code> to connect this template to Supabase.</p><div class="notice">Never put a service-role or secret key in this app.</div></section>'}
function renderLogin(){
  document.getElementById('topbar').innerHTML='<div class="topbar-inner"><div><div class="brand">Feminine Strength Co.</div><div class="name">Client Portal</div><div class="role">Your coaching space, all in one place.</div></div></div>';
  document.getElementById('main').innerHTML='<section class="login-wrap"><div class="login-card card"><div class="eyebrow">Secure client access</div><div class="title">Welcome back</div><p class="sub">Sign in to access your personal coaching dashboard.</p><form id="loginForm" class="grid" style="margin-top:18px"><div class="field"><label>Email</label><input class="input" id="email" type="email" autocomplete="email" required></div><div class="field"><label>Password</label><input class="input" id="password" type="password" autocomplete="current-password" required></div><button class="btn" type="submit">Sign in</button><button class="btn ghost" type="button" id="resetPassword">Forgot password?</button></form><div id="loginMsg" class="sub" style="margin-top:12px"></div></div></section>';
  document.getElementById('loginForm').onsubmit=async e=>{e.preventDefault();const msg=document.getElementById('loginMsg');msg.textContent='Signing in…';const {error}=await sb.auth.signInWithPassword({email:document.getElementById('email').value.trim(),password:document.getElementById('password').value});if(error){msg.textContent=error.message;return}location.reload()};
  document.getElementById('resetPassword').onclick=async()=>{const email=document.getElementById('email').value.trim();const msg=document.getElementById('loginMsg');if(!email){msg.textContent='Enter your email first.';return}const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});msg.textContent=error?'Could not send reset email.': 'Password reset email sent.'};
}
function renderNoClient(){renderTopbar('Client setup');document.getElementById('main').innerHTML='<section class="center-card card"><div class="eyebrow">Account connected</div><div class="title">Your client profile is not assigned yet.</div><p class="sub">Your login works, but there is not yet a Feminine Strength Co. client record connected to this account. Christin needs to finish your setup in Coach Hub.</p><button class="btn" id="signOut">Sign out</button></section>';document.getElementById('signOut').onclick=signOut}
function renderError(e){renderTopbar('Connection issue');document.getElementById('main').innerHTML='<section class="center-card card"><div class="eyebrow">Feminine Strength Co.</div><div class="title">We could not load your portal.</div><p class="sub">'+esc(e?.message||'Unknown error')+'</p><button class="btn" onclick="location.reload()">Try again</button></section>'}

function renderTopbar(name){
  document.getElementById('topbar').innerHTML='<div class="topbar-inner"><div><div class="brand">Feminine Strength Co.</div><div class="name" id="headerName">'+esc(name)+'</div><div class="role">Coaching platform</div></div><div class="top-actions"><button class="mode-btn '+(APP.mode==='client'?'active':'')+'" data-mode="client">Client</button>'+(isCoach()?'<button class="mode-btn '+(APP.mode==='coach'?'active':'')+'" data-mode="coach">Coach Hub</button>':'')+'<button class="icon-btn" id="logout" title="Sign out">↪</button></div></div>';
  document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>switchMode(b.dataset.mode));document.getElementById('logout').onclick=signOut;
}
function renderNav(){const nav=document.getElementById('nav');nav.classList.remove('hide');nav.innerHTML=['today','training','nutrition','movement','progress','resources'].map(x=>'<button class="'+(APP.activeTab===x?'active':'')+'" data-tab="'+x+'">'+label(x)+'</button>').join('');nav.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{APP.activeTab=b.dataset.tab;renderClientView()})}
function renderClient(){APP.mode='client';renderClientView()}
function renderClientView(){renderTopbar('Hey, '+(APP.client.preferred_name||APP.client.first_name));renderNav();document.getElementById('main').innerHTML=clientView(APP.activeTab);bindClientEvents()}
function switchMode(mode){APP.mode=mode;if(mode==='coach'){renderCoachHub();return}APP.selectedClient=null;APP.activeTab='today';loadClientData(APP.client.id).then(renderClient).catch(renderError)}

async function loadIdentity(){const {data,error}=await sb.from('profiles').select('*').eq('role','coach').limit(1);if(error)throw error;APP.profile=data?.[0]||null}
async function loadClient(userId){const {data,error}=await sb.from('clients').select('*').eq('user_id',userId).maybeSingle();if(error)throw error;APP.client=data}
async function loadClientData(clientId){
  const [w,r,ns,n,m,p,notes,cq,qs]=await Promise.all([
    sb.from('client_workouts').select('*, client_workout_exercises(*)').eq('client_id',clientId).order('scheduled_date',{ascending:true,nullsFirst:false}).order('created_at',{ascending:false}),
    sb.from('client_resources').select('*').eq('client_id',clientId).order('created_at',{ascending:false}),
    sb.from('nutrition_settings').select('*').eq('client_id',clientId).maybeSingle(),
    sb.from('nutrition_logs').select('*').eq('client_id',clientId).order('log_date',{ascending:false}).order('created_at',{ascending:false}).limit(100),
    sb.from('movement_logs').select('*').eq('client_id',clientId).order('log_date',{ascending:false}).limit(100),
    sb.from('progress_entries').select('*').eq('client_id',clientId).order('entry_date',{ascending:false}).limit(100),
    sb.from('coach_notes').select('*').eq('client_id',clientId).eq('private_to_coach',false).order('created_at',{ascending:false}),
    sb.from('checkins').select('*').eq('client_id',clientId).eq('checkin_date',today()).maybeSingle(),
    sb.from('client_checkin_questions').select('*, checkin_questions(*)').eq('client_id',clientId).eq('active',true).order('sort_order')
  ]);
  for(const x of [w,r,ns,n,m,p,notes,cq,qs])if(x.error)throw x.error;
  APP.workouts=w.data||[];APP.resources=r.data||[];APP.nutritionSettings=ns.data;APP.nutritionLogs=n.data||[];APP.movementLogs=m.data||[];APP.progressEntries=p.data||[];APP.notes=notes.data||[];APP.todayCheckin=cq.data;APP.checkinQuestions=(qs.data||[]).map(x=>x.checkin_questions).filter(Boolean);
  if(APP.todayCheckin){const {data,error}=await sb.from('checkin_responses').select('*').eq('checkin_id',APP.todayCheckin.id);if(error)throw error;APP.todayCheckin.responses={};(data||[]).forEach(r=>{const q=APP.checkinQuestions.find(x=>x.id===r.question_id);if(q)APP.todayCheckin.responses[q.field_key]=r.response})}
}
async function loadCoachHub(){
  const {data,error}=await sb.from('coach_clients').select('client_id, clients(*)').eq('coach_user_id',APP.session.user.id).order('created_at');if(error)throw error;APP.coachClients=(data||[]).map(x=>x.clients).filter(Boolean);
  const ex=await sb.from('exercises').select('*').order('name');if(ex.error)throw ex.error;APP.exercises=ex.data||[];
  const tp=await sb.from('workout_templates').select('*').eq('created_by',APP.session.user.id).order('name');if(tp.error)throw tp.error;APP.templates=tp.data||[];
}
async function loadCoachClient(clientId){const c=await sb.from('clients').select('*').eq('id',clientId).single();if(c.error)throw c.error;APP.selectedClient=c.data;await loadClientData(clientId)}

function clientView(tab){switch(tab){case'training':return trainingView();case'nutrition':return nutritionView();case'movement':return movementView();case'progress':return progressView();case'resources':return resourcesView();default:return todayView()}}
function todayView(){
  const c=APP.todayCheckin||{};const profile=APP.client.profile_data||{};const goals=Array.isArray(profile.goals)?profile.goals:[];const w=APP.workouts.find(x=>x.scheduled_date===today())||APP.workouts.find(x=>x.training_day===dayName());
  return '<div class="grid grid-main"><section class="grid"><section class="hero"><div class="eyebrow">'+fmtLong(today())+'</div><div class="title">How\'s today going?</div><div class="sub">Your plan should support you, not require you to perform perfectly.</div><div class="segment" style="margin-top:15px">'+dayTypeButtons(c._day_type)+'</div></section><section class="card"><div class="eyebrow">Today\'s rhythm</div><div class="title">'+esc(w?.name||'Your plan for today')+'</div><div class="sub">'+esc(w?.training_focus||'Your assigned programming will appear here.')+'</div>'+(w?'<button class="btn" style="margin-top:12px" data-open-workout="'+w.id+'">Open today\'s workout</button>':'')+'</section><section class="card"><div class="eyebrow">Daily check-in</div><div class="title">Protect the basics</div>'+checkinForm()+'<div class="field"><label>Anything to flag for Christin?</label><textarea class="input textarea" id="checkinFeedback" placeholder="Optional">'+esc(c.feedback||'')+'</textarea></div><button class="btn" id="saveCheckin">Save today\'s check-in</button></section></section><aside class="grid"><section class="card"><div class="eyebrow">Your coach</div><div class="coach-client"><div class="avatar">C</div><div><div class="strong">Christin</div><div class="sub">Feminine Strength Co.</div></div></div><p class="quote">'+esc(profile.coaching_message||'Let the plan meet you where you are.')+'</p></section><section class="card"><div class="eyebrow">Your focus</div><div class="list">'+(goals.map(g=>'<div class="row"><span class="label">'+esc(g)+'</span><span class="value">Focus</span></div>').join('')||'<div class="empty">Your current goals will appear here.</div>')+'</div></section></aside></div>'
}
function dayTypeButtons(active){return ['Good day','Busy day','Need to adjust'].map(x=>'<button class="seg '+(active===x?'active':'')+'" data-daytype="'+esc(x)+'">'+esc(x)+'</button>').join('')}
function trainingView(){return '<div class="grid">'+(APP.workouts.length?APP.workouts.map(workoutCard).join(''):'<section class="card empty">No workouts have been assigned yet.</section>')+'</div>'}
function workoutCard(w){const exs=(w.client_workout_exercises||[]).slice().sort((a,b)=>(a.sort_order||0)-(b.sort_order||0));return '<section class="workout"><div class="workout-head"><div><div class="wname">'+esc(w.name)+'</div><div class="wf">'+esc(w.training_focus||w.day_label||'Workout')+'</div></div><span class="dose">'+(w.completion_status==='completed'?'Completed':(w.scheduled_date?fmtDate(w.scheduled_date):'Assigned'))+'</span></div>'+(w.description?'<div class="sub" style="padding:13px 16px">'+esc(w.description)+'</div>':'')+(exs.length?exs.map(exerciseCard).join(''):'<div class="empty" style="margin:12px">Exercises will appear when your coach assigns them.</div>')+'<div style="padding:13px 16px"><button class="btn '+(w.completion_status==='completed'?'secondary':'')+'" data-complete-workout="'+w.id+'">'+(w.completion_status==='completed'?'Completed':'Mark workout complete')+'</button></div></section>'}
function exerciseCard(ex){const sets=Math.max(1,Number(ex.prescribed_sets||1));const reps=ex.prescribed_reps_min&&ex.prescribed_reps_max?ex.prescribed_reps_min+'–'+ex.prescribed_reps_max:(ex.prescribed_reps_min||ex.prescribed_reps_max||'—');let rows='';for(let i=1;i<=sets;i++)rows+='<div class="set-row"><div class="set-no">S'+i+'</div><input class="set-weight" data-set-weight="'+ex.id+'|'+i+'" inputmode="decimal" placeholder="weight"><input class="set-reps" data-set-reps="'+ex.id+'|'+i+'" inputmode="numeric" placeholder="reps"><button class="btn small secondary" data-save-set="'+ex.id+'|'+i+'">Save</button></div>';return '<div class="ex"><div class="ex-top"><div class="ex-name">'+esc(ex.exercise_name||'Exercise')+'</div><div class="dose">'+sets+' × '+esc(reps)+'</div></div>'+(ex.coaching_cues?'<div class="cue">'+esc(ex.coaching_cues)+'</div>':'')+'<div class="ex-tools">'+rows+(ex.rest_seconds?timerHtml(ex.rest_seconds,'Rest'):'')+(ex.prescribed_duration_seconds?timerHtml(ex.prescribed_duration_seconds,'Work'):'')+(ex.video_url?'<a class="video" href="'+esc(ex.video_url)+'" target="_blank" rel="noopener">▶ Watch demo</a>':'')+'</div></div>'}
function timerHtml(seconds,labelText){return '<div class="timer" data-timer="'+seconds+'"><span>'+esc(labelText)+' · '+(seconds>=60?Math.round(seconds/60)+' min':seconds+' sec')+'</span><b>'+fmtTimer(seconds)+'</b><button data-timer-start>Start</button><button class="btn small secondary" data-timer-reset>Reset</button></div>'}
function fmtTimer(s){return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}

function checkinForm(){
  if(!APP.checkinQuestions.length)return '<div class="sub">Your check-in questions will appear here once Christin assigns them.</div>';
  return '<div class="check-grid">'+APP.checkinQuestions.map(q=>{const v=APP.todayCheckin?.responses?.[q.field_key];let input;if(q.response_type==='boolean')input='<input type="checkbox" data-q="'+esc(q.field_key)+'" '+(v?'checked':'')+'>';else if(q.response_type==='scale'||q.response_type==='number')input='<input class="input" type="number" data-q="'+esc(q.field_key)+'" value="'+esc(v??'')+'" min="0" max="10">';else input='<input class="input" data-q="'+esc(q.field_key)+'" value="'+esc(v??'')+'">';return '<label class="field check-field"><span>'+esc(q.question)+'</span>'+input+'</label>'}).join('')+'</div>'
}
function nutritionView(){const s=APP.nutritionSettings||{};const logs=APP.nutritionLogs.filter(x=>x.log_date===today());const protein=logs.reduce((a,x)=>a+Number(x.protein_g||0),0);const cal=logs.reduce((a,x)=>a+Number(x.calories||0),0);return '<div class="grid grid-main"><section class="grid"><section class="card"><div class="eyebrow">Today\'s fuel</div><div class="title">'+esc(s.approach||'Nutrition tracking')+'</div><div class="grid three" style="margin:13px 0"><div class="stat"><div class="n">'+protein+'</div><div class="l">Protein g</div></div><div class="stat"><div class="n">'+cal+'</div><div class="l">Calories</div></div><div class="stat"><div class="n">'+(s.hydration_target_oz||'—')+'</div><div class="l">Water oz target</div></div></div>'+(s.notes?'<div class="sub">'+esc(s.notes)+'</div>':'')+'<div class="field"><label>Meal / food</label><input class="input" id="mealName" placeholder="e.g. chicken + rice"></div><div class="meal"><input class="input" id="mealProtein" inputmode="decimal" placeholder="protein g"><input class="input" id="mealCal" inputmode="decimal" placeholder="cal"><button class="btn small" id="addMeal">+</button></div><div class="list">'+(logs.map(m=>'<div class="row"><span class="label">'+esc(m.meal_name||'Meal')+'</span><span class="value">'+(m.protein_g||0)+'g · '+(m.calories||0)+' cal</span></div>').join('')||'<div class="empty">Nothing logged yet today.</div>')+'</div></section></section><aside class="grid"><section class="card"><div class="eyebrow">Your settings</div><div class="list">'+[['Protein target',s.protein_target_g?s.protein_target_g+' g':'—'],['Hydration target',s.hydration_target_oz?s.hydration_target_oz+' oz':'—'],['Dietary needs',(s.dietary_requirements||[]).join(', ')||'Flexible']].map(x=>'<div class="row"><span class="label">'+esc(x[0])+'</span><span class="value">'+esc(x[1])+'</span></div>').join('')+'</div></section></aside></div>'}
function movementView(){const logs=APP.movementLogs.filter(x=>x.log_date===today());return '<div class="grid grid-main"><section class="card"><div class="eyebrow">Movement & cardio</div><div class="title">Keep movement useful</div><p class="sub">Walking, steps, rowing, conditioning, or other prescribed cardio can all live here.</p><div class="field"><label>Activity</label><input class="input" id="moveType" placeholder="Walking, rower, bike…"></div><div class="meal"><input class="input" id="moveMin" inputmode="decimal" placeholder="minutes"><input class="input" id="moveSteps" inputmode="numeric" placeholder="steps"><button class="btn small" id="addMove">+</button></div><div class="field"><label>Distance (optional)</label><input class="input" id="moveDist" inputmode="decimal" placeholder="distance"></div><div class="list" style="margin-top:10px">'+(logs.map(m=>'<div class="row"><span class="label">'+esc(m.activity_type)+'</span><span class="value">'+(m.duration_minutes||0)+' min'+(m.steps?' · '+m.steps+' steps':'')+'</span></div>').join('')||'<div class="empty">No movement logged today.</div>')+'</div></section><aside class="card"><div class="eyebrow">Today</div><div class="grid three"><div class="stat"><div class="n">'+logs.length+'</div><div class="l">Logs</div></div><div class="stat"><div class="n">'+logs.reduce((a,x)=>a+Number(x.steps||0),0)+'</div><div class="l">Steps</div></div><div class="stat"><div class="n">'+logs.reduce((a,x)=>a+Number(x.duration_minutes||0),0)+'</div><div class="l">Minutes</div></div></div></aside></div>'}
function progressView(){const latest=APP.progressEntries[0];return '<div class="grid grid-main"><section class="grid"><section class="card"><div class="eyebrow">Progress</div><div class="title">Information, not judgment</div>'+(latest?'<div class="grid two" style="margin-top:12px"><div class="stat"><div class="n">'+esc(latest.value_numeric??latest.value_text??'—')+'</div><div class="l">'+esc(latest.entry_type)+' '+esc(latest.unit||'')+'</div></div><div class="stat"><div class="n">'+fmtDate(latest.entry_date)+'</div><div class="l">Latest entry</div></div></div>':'<div class="empty">No progress entries yet.</div>')+'<div class="field"><label>New progress entry</label><select class="input" id="progressType"><option value="weight">Weight</option><option value="measurement">Measurement</option><option value="performance">Performance</option><option value="other">Other</option></select><input class="input" id="progressValue" placeholder="Value or number" style="margin-top:6px"><input class="input" id="progressUnit" placeholder="Unit (lb, in, reps…)" style="margin-top:6px"><textarea class="input textarea" id="progressNote" placeholder="Optional note" style="margin-top:6px"></textarea><button class="btn" id="saveProgress" style="margin-top:6px">Save progress</button></div></section></section><aside class="card"><div class="eyebrow">History</div><div class="list">'+(APP.progressEntries.map(p=>'<div class="row"><span class="label">'+esc(p.entry_type)+' · '+fmtDate(p.entry_date)+'</span><span class="value">'+esc(p.value_numeric??p.value_text??'—')+' '+esc(p.unit||'')+'</span></div>').join('')||'<div class="empty">No history yet.</div>')+'</div></aside></div>'}
function resourcesView(){return '<div class="grid"><section class="card"><div class="eyebrow">Your resources</div><div class="title">Resources & attachments</div><div class="list">'+(APP.resources.map(resourceCard).join('')||'<div class="empty">Your coach will add resources here.</div>')+'</div></section></div>'}
function resourceCard(r){let action='';if(r.external_url)action='<a class="btn small" href="'+esc(r.external_url)+'" target="_blank" rel="noopener">Open</a>';else if(r.storage_path)action='<button class="btn small" data-file-path="'+esc(r.storage_path)+'">Open file</button>';return '<div class="resource"><div><div class="rname">'+esc(r.title)+'</div><div class="rtype">'+esc(r.resource_type||'Resource')+'</div></div>'+action+'</div>'}

function bindClientEvents(){
  document.querySelectorAll('[data-daytype]').forEach(b=>b.onclick=()=>{APP.todayCheckin=APP.todayCheckin||{client_id:APP.client.id,checkin_date:today(),responses:{}};APP.todayCheckin._day_type=b.dataset.daytype;renderClientView()});
  document.querySelectorAll('[data-open-workout]').forEach(b=>b.onclick=()=>{APP.activeTab='training';renderClientView()});
  document.querySelectorAll('[data-save-set]').forEach(b=>b.onclick=saveSet);
  document.querySelectorAll('[data-complete-workout]').forEach(b=>b.onclick=completeWorkout);
  document.querySelectorAll('[data-timer-start]').forEach(b=>b.onclick=()=>timerStart(b));document.querySelectorAll('[data-timer-reset]').forEach(b=>b.onclick=timerReset);
  document.getElementById('saveCheckin')?.addEventListener('click',saveCheckin);document.getElementById('addMeal')?.addEventListener('click',saveMeal);document.getElementById('addMove')?.addEventListener('click',saveMovement);document.getElementById('saveProgress')?.addEventListener('click',saveProgressEntry);document.querySelectorAll('[data-file-path]').forEach(b=>b.onclick=()=>openPrivateFile(b.dataset.filePath));
}
async function saveSet(e){const b=e.currentTarget;const [exerciseId,setNumber]=b.dataset.saveSet.split('|');const row=b.closest('.set-row');const payload={client_id:APP.client.id,client_workout_id:findWorkoutId(exerciseId),client_workout_exercise_id:exerciseId,set_number:Number(setNumber),weight:Number(row.querySelector('.set-weight').value)||null,reps_completed:Number(row.querySelector('.set-reps').value)||null,completed:true,logged_at:new Date().toISOString()};const old=await sb.from('workout_set_logs').select('id').eq('client_workout_exercise_id',exerciseId).eq('set_number',Number(setNumber)).maybeSingle();let result=old.data?await sb.from('workout_set_logs').update(payload).eq('id',old.data.id):await sb.from('workout_set_logs').insert(payload);if(result.error){errorToast(result.error.message);return}toast('Set saved')}
async function completeWorkout(e){const id=e.currentTarget.dataset.completeWorkout;const {error}=await sb.from('client_workouts').update({completion_status:'completed'}).eq('id',id);if(error){errorToast(error.message);return}await loadClientData(APP.client.id);renderClientView();toast('Workout marked complete')}
function findWorkoutId(exerciseId){for(const w of APP.workouts)if((w.client_workout_exercises||[]).some(e=>e.id===exerciseId))return w.id;return null}
async function saveCheckin(){const responses={};document.querySelectorAll('[data-q]').forEach(el=>responses[el.dataset.q]=el.type==='checkbox'?el.checked:el.value);const fields={client_id:APP.client.id,checkin_date:today(),feedback:document.getElementById('checkinFeedback')?.value.trim()||null};const map={energy:'energy',sleep:'sleep',stress:'stress',recovery:'recovery',hydration:'hydration',nutrition_adherence:'nutrition_adherence',movement:'movement'};Object.keys(responses).forEach(k=>{if(map[k])fields[map[k]]=responses[k]===''?null:Number(responses[k])});let checkinId=APP.todayCheckin?.id;let result;if(checkinId)result=await sb.from('checkins').update(fields).eq('id',checkinId);else{result=await sb.from('checkins').insert(fields).select().single();checkinId=result.data?.id}if(result.error){errorToast(result.error.message);return}for(const [key,val] of Object.entries(responses)){const q=APP.checkinQuestions.find(x=>x.field_key===key);if(!q)continue;const old=await sb.from('checkin_responses').select('id').eq('checkin_id',checkinId).eq('question_id',q.id).maybeSingle();const r=old.data?await sb.from('checkin_responses').update({response:val}).eq('id',old.data.id):await sb.from('checkin_responses').insert({checkin_id:checkinId,question_id:q.id,response:val});if(r.error){errorToast(r.error.message);return}}await loadClientData(APP.client.id);toast('Check-in saved');renderClientView()}
async function saveMeal(){const name=document.getElementById('mealName').value.trim();if(!name)return;const {error}=await sb.from('nutrition_logs').insert({client_id:APP.client.id,log_date:today(),meal_name:name,protein_g:Number(document.getElementById('mealProtein').value)||null,calories:Number(document.getElementById('mealCal').value)||null});if(error){errorToast(error.message);return}await loadClientData(APP.client.id);toast('Nutrition logged');renderClientView()}
async function saveMovement(){const type=document.getElementById('moveType').value.trim();if(!type)return;const {error}=await sb.from('movement_logs').insert({client_id:APP.client.id,log_date:today(),activity_type:type,duration_minutes:Number(document.getElementById('moveMin').value)||null,steps:Number(document.getElementById('moveSteps').value)||null,distance:Number(document.getElementById('moveDist').value)||null});if(error){errorToast(error.message);return}await loadClientData(APP.client.id);toast('Movement logged');renderClientView()}
async function saveProgressEntry(){const value=document.getElementById('progressValue').value.trim();const numeric=Number(value);const payload={client_id:APP.client.id,entry_date:today(),entry_type:document.getElementById('progressType').value,value_numeric:value&&Number.isFinite(numeric)?numeric:null,value_text:value&&!Number.isFinite(numeric)?value:null,unit:document.getElementById('progressUnit').value.trim()||null,notes:document.getElementById('progressNote').value.trim()||null};const {error}=await sb.from('progress_entries').insert(payload);if(error){errorToast(error.message);return}await loadClientData(APP.client.id);toast('Progress saved');renderClientView()}
function timerStart(btn){const box=btn.closest('[data-timer]');if(APP.timers.has(box))return;let remaining=Number(box.dataset.timer);const out=box.querySelector('b');btn.textContent='Pause';const id=setInterval(()=>{remaining--;out.textContent=fmtTimer(remaining);if(remaining<=0){clearInterval(id);APP.timers.delete(box);btn.textContent='Start';out.textContent=fmtTimer(Number(box.dataset.timer));navigator.vibrate?.([200,100,200]);toast('Timer complete')}},1000);APP.timers.set(box,id);btn.onclick=()=>{clearInterval(id);APP.timers.delete(box);btn.textContent='Start';timerStart(btn)}}
function timerReset(btn){const box=btn.closest('[data-timer]');const id=APP.timers.get(box);if(id)clearInterval(id);APP.timers.delete(box);box.querySelector('b').textContent=fmtTimer(Number(box.dataset.timer));box.querySelector('[data-timer-start]').textContent='Start'}
async function openPrivateFile(path){const {data,error}=await sb.storage.from('client-attachments').createSignedUrl(path,300);if(error){errorToast(error.message);return}window.open(data.signedUrl,'_blank','noopener')}

function renderCoachHub(){
  renderTopbar('Coach Hub');document.getElementById('nav').classList.add('hide');document.getElementById('main').innerHTML='<div class="grid grid-main"><section class="grid"><section class="hero"><div class="eyebrow">Coach Hub</div><div class="title">Feminine Strength Co.</div><div class="sub">One platform, many clients. Select a client to review their individual programming and data.</div></section><section class="card"><div class="card-head"><div><div class="eyebrow">Clients</div><div class="title">Your roster</div></div><button class="btn small" id="refreshCoach">Refresh</button></div><div class="client-list">'+(APP.coachClients.map(c=>'<button class="client-row" data-select-client="'+c.id+'"><span class="avatar">'+initials(c.preferred_name||c.first_name)+'</span><span><strong>'+esc((c.preferred_name||c.first_name)+' '+(c.last_name||''))+'</strong><em>'+esc(c.status||'active')+'</em></span><b>Open →</b></button>').join('')||'<div class="empty">No clients are assigned to this coach yet.</div>')+'</div></section></section><aside class="grid"><section class="card"><div class="eyebrow">Reusable library</div><div class="title">Platform assets</div><div class="grid two"><div class="stat"><div class="n">'+APP.exercises.length+'</div><div class="l">Exercises</div></div><div class="stat"><div class="n">'+APP.templates.length+'</div><div class="l">Templates</div></div></div><p class="sub" style="margin-top:12px">Exercises and workout templates are reusable. Client assignments remain client-specific.</p></section><section class="card"><div class="eyebrow">Security</div><div class="good">Authenticated access + Row Level Security are active for the master platform.</div></section></aside></div>';
  document.querySelectorAll('[data-select-client]').forEach(b=>b.onclick=async()=>{setLoading(true);try{await loadCoachClient(b.dataset.selectClient);renderSelectedCoachClient()}catch(e){renderError(e)}finally{setLoading(false)}});document.getElementById('refreshCoach').onclick=async()=>{await loadCoachHub();renderCoachHub()}
}
function renderSelectedCoachClient(){const c=currentClient();renderTopbar(c.preferred_name||c.first_name);document.getElementById('nav').classList.add('hide');const responses=APP.todayCheckin?.responses||{};document.getElementById('main').innerHTML='<div class="grid"><section class="hero"><div class="eyebrow">Coach Hub · Client</div><div class="title">'+esc((c.preferred_name||c.first_name)+' '+(c.last_name||''))+'</div><div class="sub">Reviewing this client\'s data only. Programming remains client-specific.</div><div class="coach-actions"><button class="btn taupe" id="backClients">← All clients</button><button class="btn secondary" id="addNote">Add private note</button></div></section><section class="grid grid-main"><section class="grid"><section class="card"><div class="eyebrow">Today\'s check-in</div><div class="title">Readiness snapshot</div>'+(APP.todayCheckin?'<div class="list"><div class="row"><span class="label">Date</span><span class="value">'+fmtDate(APP.todayCheckin.checkin_date)+'</span></div>'+Object.entries(responses).map(x=>'<div class="row"><span class="label">'+esc(x[0])+'</span><span class="value">'+esc(typeof x[1]==='boolean'?(x[1]?'Yes':'No'):x[1])+'</span></div>').join('')+(APP.todayCheckin.feedback?'<div class="notice">'+esc(APP.todayCheckin.feedback)+'</div>':'')+'</div>':'<div class="empty">No check-in today.</div>')+'</section><section class="card"><div class="eyebrow">Programming</div><div class="title">Assigned workouts</div>'+(APP.workouts.map(w=>'<div class="row"><span class="label">'+esc(w.name)+'</span><span class="value">'+esc(w.scheduled_date?fmtDate(w.scheduled_date):w.training_focus||w.day_label||'Assigned')+'</span></div>').join('')||'<div class="empty">No workouts assigned.</div>')+'</section></section><aside class="grid"><section class="card"><div class="eyebrow">Client record</div><div class="coach-client"><div class="avatar">'+initials(c.preferred_name||c.first_name)+'</div><div><div class="strong">'+esc(c.email||'')+'</div><div class="sub">'+esc(c.status||'active')+'</div></div></div><div class="list" style="margin-top:12px"><div class="row"><span class="label">Goals</span><span class="value">'+esc((c.profile_data?.goals||[]).join(' · ')||'—')+'</span></div><div class="row"><span class="label">Private files</span><span class="value">Enabled</span></div></div></section><section class="card"><div class="eyebrow">Private coach notes</div><div class="list">'+(APP.notes.map(n=>'<div class="row"><span class="label">'+esc(n.note)+'</span><span class="value">'+fmtDate((n.created_at||'').slice(0,10))+'</span></div>').join('')||'<div class="empty">No notes yet.</div>')+'</div></section></aside></section></div>';
  document.getElementById('backClients').onclick=()=>{APP.selectedClient=null;renderCoachHub()};document.getElementById('addNote').onclick=openNoteModal
}
function openNoteModal(){const m=document.getElementById('modal');m.innerHTML='<div class="modal"><div class="modal-head"><div><div class="eyebrow">Private coach note</div><div class="title">'+esc(currentClient().preferred_name||currentClient().first_name)+'</div></div><button class="close" id="closeModal">×</button></div><textarea class="input textarea" id="coachNoteText" placeholder="What should be remembered for this client?"></textarea><button class="btn" id="saveCoachNote" style="margin-top:10px">Save note</button></div>';m.classList.add('open');document.getElementById('closeModal').onclick=closeModal;document.getElementById('saveCoachNote').onclick=async()=>{const note=document.getElementById('coachNoteText').value.trim();if(!note)return;const {error}=await sb.from('coach_notes').insert({client_id:currentClient().id,coach_user_id:APP.session.user.id,note,private_to_coach:true});if(error){errorToast(error.message);return}closeModal();await loadClientData(currentClient().id);renderSelectedCoachClient();toast('Private note saved')}}
function closeModal(){document.getElementById('modal').classList.remove('open')}
async function signOut(){await sb.auth.signOut();location.reload()}
window.closeModal=closeModal;
window.addEventListener('DOMContentLoaded',init);
